### PR TITLE
ci: migrate to GH Actions

### LINKED ISSUE #74: ci: move to GitHub Actions
I'd like to contribute the the HTSInfer repo too.

I see you are still running on _Travis_, I could transfer the CI to _GH Actions_. I like setting up CIs, I do this for fun :)

Would you like that @uniqueg?

### PR DESCRIPTION
**Pull request by AngryMaciek**
### Description

GitHub Actions are more powerful, flexible and popular.  
We should move CI to the native GH mechanism on the platform.

Fixes #74 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist

Please carefully read these items and tick them off if the statements are true
_or do not apply_.

- [x] I have performed a self-review of my own code
- [x] My code follows the existing coding style, lints and generates no new
      warnings
- [x] I have added type annotations to all function/method signatures, and I
      have added type annotations for any local variables that are non-trivial,
      potentially ambiguous or might otherwise benefit from explicit typing.
- [x] I have commented my code in hard-to-understand areas
- [x] I have added ["Google-style docstrings"] to all new modules, classes,
      methods/functions or updated previously existing ones
- [x] I have added tests that prove my fix is effective or that my feature
      works
- [x] New and existing unit tests pass locally with my changes and I have not
      reduced the code coverage relative to the previous state
- [x] I have updated any sections of the app's documentation that are affected
      by the proposed changes

If for some reason you are unable to tick off all boxes, please leave a
comment explaining the issue you are facing so that we can work on it
together.

### CODE REVIEW

**Comment by AngryMaciek** [comment]
This is still a WIP but I need @uniqueg to take a look at the following issues:

* `pylint` raises issues, not sure how the current `dev_v2` passed since I did not touch the code at all.
* `coveralls` requires GITHUB TOKEN specification

I did not include yet the following part:
```
- git config --global user.name "semantic-release (via TravisCI)"
- git config --global user.email "semantic-release@travis"
- semantic-release publish -v DEBUG
```

Is that required? What is this for?

Could you please unhook the repo from the Travis account?

**Comment by uniqueg** [comment]
> This is still a WIP but I need @uniqueg to take a look at the following issues:
> 
> * `pylint` raises issues, not sure how the current `dev_v2` passed since I did not touch the code at all.
> * `coveralls` requires GITHUB TOKEN specification
> 
> I did not include yet the following part:
> 
> ```
> - git config --global user.name "semantic-release (via TravisCI)"
> - git config --global user.email "semantic-release@travis"
> - semantic-release publish -v DEBUG
> ```
> 
> Is that required? What is this for?
> 
> Could you please unhook the repo from the Travis account?

Thanks a lot @AngryMaciek. I have made you admin and removed the checks for Travis and Coveralls that didn't run. All other issues are addressed in zavolanlab/zarp-cli/pull/27, as well as the review of the GH Actions configs (just the one comment re: `style.yml` naming).

**Comment by uniqueg** [comment]
Also please mind [this comment](https://github.com/zavolanlab/zarp-cli/pull/27#issuecomment-1082252869)

**Comment by AngryMaciek** [comment]
Hey @uniqueg,  
Included suggested changes, please see [this post](https://github.com/zavolanlab/zarp-cli/pull/27#issuecomment-1091599862) for more info.
One thing different here is that in this case the semantic release CI workflow fails because, unlike for _zarp-cli_, you did not set release configuration in `setup.cfg`.

**Review by uniqueg — APPROVED** [review]

**Pull request merged**
