### PR TITLE
refactor: pass conf instances, not individual args #92

### LINKED ISSUE #84: Refactor argument passing to class instances
**Is your feature request related to a problem? Please describe.**

Currently, arguments are passed to class constructors individually. This has several disadvantages:

- Arguments need to be described in multiple locations (e.g., CLI interface, `HtsIinfer` class, classes for each inference functionality)
- Adding new arguments to classes requires code changes in multiple modules
- Constructor interfaces become unwieldy; `pylint` messages that warn against unwieldy interfaces were globally disabled (specifically: `R0902: too-many-instance-attributes` and `R0903: too-many-arguments`)

**Describe the solution you'd like**

- [x] Define a (Pydantic) configuration model `Args` with all command-line arguments in [`htsinfer/models.py`](https://github.com/zavolanlab/htsinfer/blob/dev/htsinfer/models.py); add appropriate defaults
- [x] Define a (Pydantic) configuration model `Config` in [`htsinfer/models.py`](https://github.com/zavolanlab/htsinfer/blob/dev/htsinfer/models.py) with properties `args` of type `htsinfer.models.Args` and `results` of type `htsinfer.models.Results`
- [x] Instantiate an instance of the model in the `HTSinfer` class constructor - which will then take only two arguments, `args` and `results`, both optional, with defaults being specified in `models.py`
- [ ] Pass arguments in bulk to `Args()` in `HtsInfer` instantiation in [`htsinfer/cli.py`](https://github.com/zavolanlab/htsinfer/blob/dev/htsinfer/cli.py)
- [ ] Redefine constructors of classes in all other modules (e.g., `GetLibSource`, `GetReadOrientation`) such that they only take a single argument, `config` of type `htsinfer.models.Config`; collapse separate classes for handling two or only one input file into one, where applicable (newer functionalities use only a single class) as there is no solid reason to keep these separate, again causing repetition of descriptions and sometimes code
- [x] Refactor calls to instantiate the modified classes in [`htsinfer/htsinfer.py`](https://github.com/zavolanlab/htsinfer/blob/dev/htsinfer/htsinfer.py) so that only a single argument `config` is passed

**Describe alternatives you've considered**

N/A

**Additional context**

Following the suggested solution still requires arguments to be described in two places: the model definition in [`htsinfer/models.py`]
https://github.com/zavolanlab/htsinfer/blob/dev/htsinfer/models.py) and the CLI definition in [`htsinfer/cli.py`](https://github.com/zavolanlab/htsinfer/blob/dev/htsinfer/cli.py). An ideal solution would re-use the definitions from `model.py` in model for `argparse` help messages in `cli.py`. However, this is likely not trivial and should probably constitute a separate issue.

### LINKED ISSUE #93: pytest issue on macOS Big Sur
**Describe the bug**
Os-dependent issue when testing the installation of development/testing dependencies.
Error is: `htsinfer.exceptions.StarProblem: Failed to create STAR index`
If solved then: `htsinfer.exceptions.StarProblem: Failed to generate STAR alignments`

**To Reproduce**

1. Use computer with macOS Big Sur and Miniconda(4.12.0) installation.
2. Follow the Installation tutorial for `htsinfer`.

**Expected behavior**
To pass all tests.

**Desktop (please complete the following information):**

- OS: macOS Big Sur

**Additional context**
The problem solution is trivial although not up to me to decide 
if it should be a part of the codebase.

**Solution**
In file `htsinfer/htsinfer/get_read_orientation.py` (dev branch)
Add `index_dir.mkdir(parents=True, exist_ok=True)` in line 255.
Add `Path(out_dir).mkdir(parents=True, exist_ok=True)` in line 319.

### PR DESCRIPTION
**Pull request by BorisYourich**
### Description

Refactor argument passing to inference classes (#84)
Fix `pytest` issue on MacOS (#93)

* Pydantic configuration models `Args` and `Config` were defined and implemented
* The individual arguments of the HtsInfer class were removed and only a single non-optional argument `config` was added
* All of the attributes except `run_id` and `state` were removed as they are identical to `config.args` class attributes
* The previously used `self.results` attribute has been replaced by `self.config.results` because of redundancy
* Tests were modified to work with the refactored codebase
* Directories for STAR alignment and genome indexing are created in the script (#93)
* Minor changes in the code where deemed useful e.g. variable `orientation` removed from get_read_orientation.evaluate() due to redundancy.

Fixes #84
Fixes #93

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation update

### Checklist

Please carefully read these items and tick them off if the statements are true
_or do not apply_.

- [x] I have performed a self-review of my own code
- [x] My code follows the existing coding style, lints and generates no new
      warnings 
- [x] I have added type annotations to all function/method signatures, and I
      have added type annotations for any local variables that are non-trivial,
      potentially ambiguous or might otherwise benefit from explicit typing.
- [x] I have commented my code in hard-to-understand areas
- [x] I have added ["Google-style docstrings"] to all new modules, classes,
      methods/functions or updated previously existing ones
- [x] I have added tests that prove my fix is effective or that my feature
      works
- [x] New and existing unit tests pass locally with my changes and I have not
      reduced the code coverage relative to the previous state
- [x] I have updated any sections of the app's documentation that are affected
      by the proposed changes

If for some reason you are unable to tick off all boxes, please leave a
comment explaining the issue you are facing so that we can work on it
together.

### CODE REVIEW

**Review by uniqueg — APPROVED** [review]
Fantastic - thanks a lot @BorisYourich!

**Review by uniqueg — CHANGES_REQUESTED** [review]
Just saw that there are now 5 lines in `htsinfer/htsinfer.py` that are not covered in unit tests (when a `WorkEnvProblem` is raised. I suppose that this wasn't yet a thing before the last couple of merges.

Would you mind including a test for these before I merge, @BorisYourich?

Also, I'm wondering why the CodeCov report was not triggered for this PR. Any idea? Compare #92 - there the CodeCov report is there and clearly indicates that the coverage drops

**Comment by BorisYourich** [comment]
Hey @uniqueg, I just went through the CodeCov report and it seems it is complaining about lines of code covered in tests. Specifically, it is the __test_evaluate_work_env_problem__ on the 173rd line and and the __test_clean_up_tmp_dir_removal_fails__ on the 344th line in the __test_htsinfer.py__ in my branch. I have no idea why it is marked as missed in CodeCov though.

**Comment by uniqueg** [comment]
I'll have a look, maybe tomorrow. In principle I would tend to trust `coverage` to do its thing. Sure your tests cover the specific conditions that would lead execution down the path of the missed statements?

**Comment by BorisYourich** [comment]
My bad, I just realised where the problem is, the tests are there, but they do not work properly as I missed a change that was required due to refactoring of the code. I will fix it, you needn't worry.

**Comment by BorisYourich** [comment]
@uniqueg Coverage at 100%, ready to merge.

**Review by uniqueg — APPROVED** [review]

**Pull request merged**
