### PR TITLE
fix: remove transcript duplicates

### LINKED ISSUE #116: Remove duplicates from transcripts file
As discussed in #115, there are 3 duplicate sequences in the `data/transcripts.fasta.gz`, that can cause a parse error during the aligment step of STAR. 
```
RPS2|YGL123W|YGL123W_mRNA|scerevisiae|4932
RPS3|YNL178W|YNL178W_mRNA|scerevisiae|4932
RPS5|YJR123W|YJR123W_mRNA|scerevisiae|4932
```
These are likely some artifacts and should be removed.

### PR DESCRIPTION
**Pull request by balajtimate**
Removed 3 transcript duplicates from `data/transcripts.fasta.gz` that were causing issues with STAR alignment. 

Fixes #116 

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### Checklist

Please carefully read these items and tick them off if the statements are true
_or do not apply_.

- [X] I have performed a self-review of my own code
- [X] My code follows the existing coding style, lints and generates no new
      warnings
- [X] I have added type annotations to all function/method signatures, and I
      have added type annotations for any local variables that are non-trivial,
      potentially ambiguous or might otherwise benefit from explicit typing.
- [X] I have commented my code in hard-to-understand areas
- [X] I have added ["Google-style docstrings"] to all new modules, classes,
      methods/functions or updated previously existing ones
- [X] I have added tests that prove my fix is effective or that my feature
      works
- [X] New and existing unit tests pass locally with my changes and I have not
      reduced the code coverage relative to the previous state
- [X] I have updated any sections of the app's documentation that are affected
      by the proposed changes

If for some reason you are unable to tick off all boxes, please leave a
comment explaining the issue you are facing so that we can work on it
together.

### CODE REVIEW

**Review by uniqueg — DISMISSED** [review]
I guess that's good to merge as it is. But if you like you could use that same PR to also get rid of the copy of the `transcripts.fasta.gz` file at `htsinfer/data/`.

**Comment by balajtimate** [comment]
Sure, I removed that copy (it was actually a `transcript.fasta.zip` file, but not used anywhere).

**Comment by uniqueg** [comment]
Any ideas why the tests are failing?

**Comment by balajtimate** [comment]
I'm not sure, maybe because I pushed the branch while the PR tests were still running? 
I just reran them and they seem fine now.

**Comment by uniqueg** [comment]
What on earth is happening with Cutadapt? Why does it take _hours_? Any idea? It didn't use to do that and we need to fix that ASAP, or else we will run out of free minutes for GitHub Actions

**Comment by uniqueg** [comment]
> What on earth is happening with Cutadapt? Why does it take _hours_? Any idea? It didn't use to do that and we need to fix that ASAP, or else we will run out of free minutes for GitHub Actions

Fixed with #119

**Review by uniqueg — APPROVED** [review]

**Pull request merged**
