### PR TITLE
Issue17: Extend motifs

### LINKED ISSUE #17: Extend motifs based on nucleotide representation in sequenced reads
Given a set of core motifs, check whether they represent parts of longer motifs in sequenced reads. Extend left and right if the nucleotide composition in these positions is very biased. That is, starting from all occurrences of a core motif in the reads, determine the frequencies of A,C,G,T at the left- and right-flanking positions, and calculate the entropy of this distribution. Ideally, the motif can be extended if the flanking positions contain one specific nucleotide, i.e. entropy is 0. But sequencing errors could introduce some noise. So it may be necessary to introduce a cutoff. Continue the extension greedily until the entropy becomes too high.

### PR DESCRIPTION
**Pull request by stinea98**
### Description

Please include a summarized description of the change(s) and which issue(s)
this pull request addresses, if any. Please include relevant motivation and
context, unless already duly described in an associated issue or resource.
Make sure to list any dependencies that are required for this change.

Fixes # (issue)

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality
      to not work as expected)
- [ ] Documentation update

### Checklist

Please carefully read these items and tick them off if the statements are true
_or do not apply_.

- [x] I have performed a self-review of my own code
- [x] My code follows the existing coding style, lints and generates no new
      warnings
- [x] I have added type annotations to all function/method signatures, and I
      have added type annotations for any local variables that are non-trivial,
      potentially ambiguous or might otherwise benefit from explicit typing.
- [x] I have commented my code in hard-to-understand areas
- [x] I have added ["Google-style docstrings"] to all new modules, classes,
      methods/functions or updated previously existing ones
- [x] I have added tests that prove my fix is effective or that my feature
      works
- [x] New and existing unit tests pass locally with my changes and I have not
      reduced the code coverage relative to the previous state
- [x] I have updated any sections of the app's documentation that are affected
      by the proposed changes

If for some reason you are unable to tick off all boxes, please leave a
comment explaining the issue you are facing so that we can work on it
together.

### CODE REVIEW

**Comment by stinea98** [comment]
Question: I am using the **scipy.stats** package in my code and I'm importing it with `from scipy import stats` but get the error _ModuleNotFoundError: No module named 'scipy'_ ... How can I import the scipy.stats package, i.e. in which of the files should I add the scipy.stats package?

**Comment by stinea98** [comment]
Question 2: I'm not sure what the value of the cutoff should be (atm I've set it to cutoff=0.1). But I guess this depends on the length of the sequences and the length of the core_motifs... How long would these typically be? Or do you have a suggestion for a specific cutoff value?

**Comment by mzavolan** [comment]
> Question: I am using the **scipy.stats** package in my code and I'm importing it with `from scipy import stats` but get the error _ModuleNotFoundError: No module named 'scipy'_ ... How can I import the scipy.stats package, i.e. in which of the files should I add the scipy.stats package?

You probably don't have the module installed on your machine. You would need to install via conda or pip.

**Comment by mzavolan** [comment]
> Question 2: I'm not sure what the value of the cutoff should be (atm I've set it to cutoff=0.1). But I guess this depends on the length of the sequences and the length of the core_motifs... How long would these typically be? Or do you have a suggestion for a specific cutoff value?

The cutoff should be a parameter to this function.

**Comment by stinea98** [comment]
> The cutoff should be a parameter to this function.

Ok, then I'll change this in the code!

**Comment by stinea98** [comment]
> > Question: I am using the **scipy.stats** package in my code and I'm importing it with `from scipy import stats` but get the error _ModuleNotFoundError: No module named 'scipy'_ ... How can I import the scipy.stats package, i.e. in which of the files should I add the scipy.stats package?
> 
> You probably don't have the module installed on your machine. You would need to install via conda or pip.

Sorry, guess I formulated the question unclear - I meant in the htsinfer package! It runs on my machine, but just not in the checks on the pull request. Do I have to include scipy in the environment.yml file in the htsinfer folder?

**Comment by uniqueg** [comment]
@stinea98: correct, every package that is required by the code needs to go inside the `environment.yml` file, else the virtual machine that Travis runs the test on wouldn't know which packages it should install before executing the code

**Comment by stinea98** [comment]
> @stinea98: correct, every package that is required by the code needs to go inside the `environment.yml` file, else the virtual machine that Travis runs the test on wouldn't know which packages it should install before executing the code

makes sense, thanks! I still have problems figuring out where exactly to put scipy and numpy... I tried this, but it didn't work and didn't manage to find a fix online...
`name: htsinfer
channels:
  - defaults
  - bioconda
dependencies:
  - biopython=1.78
  - pip=20.2.3
  - python=3.8.5
  - pip:
    - -e .
    - scipy=1.5.4
    - numpy=1.19.4`

**Comment by uniqueg** [comment]
Check carefully to make sure code adheres to spec defined in #17 and resolve any open issues.

**Pull request closed without merging**
