### PR TITLE
Infer polyA tail & Conda to Mamba

### LINKED ISSUE #86: Infer presence of polyA tails in reads
**Is your feature request related to a problem? Please describe.**
TBA

**Describe the solution you'd like**
TBA

**Describe alternatives you've considered**
TBA

**Additional context**
TBA

### LINKED ISSUE #101: Change from conda to mamba in CI workflows
**Describe the bug**
The current CI workflow uses conda to set up the work environment. It is very slow and workflow run times can climb up to almost 30 minutes.

**To Reproduce**
Push or Pull request

**Expected behavior**
```conda-incubator/setup-miniconda@v2``` offers the Experimental ``` mamba-version: "*" ``` option which enables mamba as the default package manager.
It would be reasonable to use mamba since the run is ~10 times faster.

### PR DESCRIPTION
**Pull request by BorisYourich**
### Description

Fixes #86
Fixes #101 

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality
      to not work as expected)
- [x] Documentation update

### Checklist

Please carefully read these items and tick them off if the statements are true
_or do not apply_.

- [x] I have performed a self-review of my own code
- [x] My code follows the existing coding style, lints and generates no new
      warnings
- [x] I have added type annotations to all function/method signatures, and I
      have added type annotations for any local variables that are non-trivial,
      potentially ambiguous or might otherwise benefit from explicit typing.
- [x] I have commented my code in hard-to-understand areas
- [x] I have added ["Google-style docstrings"] to all new modules, classes,
      methods/functions or updated previously existing ones
- [x] I have added tests that prove my fix is effective or that my feature
      works
- [x] New and existing unit tests pass locally with my changes and I have not
      reduced the code coverage relative to the previous state
- [x] I have updated any sections of the app's documentation that are affected
      by the proposed changes

If for some reason you are unable to tick off all boxes, please leave a
comment explaining the issue you are facing so that we can work on it
together.

### CODE REVIEW

**Review by uniqueg — COMMENTED** [review]
EDIT: Okay, I read the PR description :)

EDIT2: But PR #99 is closed, now I'm confused. In what order should PRs be merged? It would make sense to me to start with _this_ one (after removing the polyA-related stuff).

Mamba changes look fine, but the PR still contains polyA changes. Is it supposed to be merged after the PR with those changes?

**Comment by BorisYourich** [comment]
> EDIT: Okay, I read the PR description :)
> 
> EDIT2: But PR #99 is closed, now I'm confused. In what order should PRs be merged? It would make sense to me to start with _this_ one (after removing the polyA-related stuff).
> 
> Mamba changes look fine, but the PR still contains polyA changes. Is it supposed to be merged after the PR with those changes?

Not necessarily, it was intended in that order, but the previous PR contains just the subset of changes of this one. This branch was created from the polyA_tails branch so that when the polyA_tails is merged this one does not have any conflicts, but since the polyA is closed, you might as well just merge this one, which has both the CI as well as polyA changes.

**Comment by uniqueg** [comment]
Yes, but that is the problem: the PR title and description does not reflect that! And so if I squash merge, there will be no entry in the history that will mention or describe the polyA tail code. And if I don't squash, we will get 7 commits for partial implementations, including a revert. What we want instead is two commits, one for the Mamba vs Conda change, the other for the polyA tail functionality. Two options here:
1. You do `git rebase --interactive` on this branch and clean it up such that there are 2 properly named conventional commits (one `build: use Mamba instead of Conda` and one `feat: infer presence of polyA tail`).
2. You create two PRs from two separate feature branches, one addressing the Conda/Mamba change, the other the polyA tail change.

The second option is generally preferred because I can review independently. But in this case I'm fine with either.

**Comment by BorisYourich** [comment]
Yeah sure, I did not expect you would close the first one :D, will keep this in mind if I ever make two or more consecutive PRs in the future. I will go with rebase just to keep it simple for now.

**Comment by uniqueg** [comment]
Oh, my bad, I misunderstood. Could have just reopened #99 then.

**Review by uniqueg — APPROVED** [review]

**Pull request merged**
