### PR TITLE
chore: configure GitHub Codespaces for this project

### PR DESCRIPTION
**Pull request by AngryMaciek**
### Description

So: I was really bored yesterday and decided to learn the [GitHub Codespaces](https://github.com/features/codespaces) mechanism to set up a Cloud dev IDE. These are pretty cool - a whole development environment set up automatically in a container, accessible from a browser. AFAIK works fine; the README badge will become active upon merge to `dev` branch (currently configuration files are not there yet). In order to test it yourself go to repo page, switch to `codespaces` branch click green button _Code_, then _Codespaces_ and another green button to create a codespace.

### Type of change

- [x] Other

### Checklist

Please carefully read these items and tick them off if the statements are true
_or do not apply_.

- [x] I have performed a self-review of my own code
- [ ] ~My code follows the existing coding style, lints and generates no new
      warnings~
- [ ] ~I have added type annotations to all function/method signatures, and I
      have added type annotations for any local variables that are non-trivial,
      potentially ambiguous or might otherwise benefit from explicit typing.~
- [x] I have commented my code in hard-to-understand areas
- [ ] ~I have added ["Google-style docstrings"] to all new modules, classes,
      methods/functions or updated previously existing ones~
- [ ] ~I have added tests that prove my fix is effective or that my feature
      works~
- [ ] ~New and existing unit tests pass locally with my changes and I have not
      reduced the code coverage relative to the previous state~
- [ ] ~I have updated any sections of the app's documentation that are affected
      by the proposed changes~

If for some reason you are unable to tick off all boxes, please leave a
comment explaining the issue you are facing so that we can work on it
together.

### CODE REVIEW

**Comment by AngryMaciek** [comment]
Org admin needs to adjust the [Codespace billing settings](https://docs.github.com/en/billing/managing-billing-for-github-codespaces/managing-the-spending-limit-for-github-codespaces#managing-the-github-codespaces-spending-limit-for-your-organization-account) so that the org does not pay for everyone who creates Codespaces (see below), rather that you should enforce "Individual billing", i.e. every user pays up from their pool of free codespace minutes (everyone has a personal pool of minutes as for ci).

Screenshot 2023-04-17 at 18 56 27

**Comment by AngryMaciek** [comment]
(?)

**Comment by uniqueg** [comment]
:-)

**Review by uniqueg — COMMENTED** [review]
Will not use Codespaces in HTSinfer for now, but good to refer to this PR when we try out Codespaces and see if it can be useful for us, so please let's not delete the branch

**Pull request closed without merging**
