### PR TITLE
Issue35_motif_search_Dhryata_Kamdar

### LINKED ISSUE #35: Find motif matches within a read
For constructing the position-dependent profile of motif occurrences and counting the reads that match individual motifs (issues #18 and #19), we need a functionality of finding where a specific motif occurs within a read. We could do this by sliding the motif from left to right, starting from a minimum overlap between motif end and read start and ending at some minimum overlap between motif start and read end, reporting all of the consistent matches as a list of tuples, (position:fraction of motif matched). Running this function over all reads and all motifs will be time-consuming, so minimize the number of tests that are done to decide whether the motif matches or not.

### PR DESCRIPTION
**Pull request by Dhryata**
### Description

Tackling Issue #35
For constructing the position-dependent profile of motif occurrences and counting the reads that match individual motifs (issues #18 and #19), we need a functionality of finding where a specific motif occurs within a read. We could do this by sliding the motif from left to right, starting from a minimum overlap between motif end and read start and ending at some minimum overlap between motif start and read end, reporting all of the consistent matches as a list of tuples, (position:fraction of motif matched). Running this function over all reads and all motifs will be time-consuming, so minimize the number of tests that are done to decide whether the motif matches or not.

Fixes Issue # 35

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality
      to not work as expected)
- [ ] Documentation update

### Checklist

Please carefully read these items and tick them off if the statements are true
_or do not apply_.

- [x] I have performed a self-review of my own code
- [x] My code follows the existing coding style, lints and generates no new
      warnings
- [ ] I have added type annotations to all function/method signatures, and I
      have added type annotations for any local variables that are non-trivial,
      potentially ambiguous or might otherwise benefit from explicit typing.
- [x] I have commented my code in hard-to-understand areas
- [x] I have added ["Google-style docstrings"] to all new modules, classes,
      methods/functions or updated previously existing ones
- [x] I have added tests that prove my fix is effective or that my feature
      works
- [x] New and existing unit tests pass locally with my changes and I have not
      reduced the code coverage relative to the previous state
- [ ] I have updated any sections of the app's documentation that are affected
      by the proposed changes

If for some reason you are unable to tick off all boxes, please leave a
comment explaining the issue you are facing so that we can work on it
together.

### CODE REVIEW

**Comment by Dhryata** [comment]
@uniqueg Dear Prof, I am not sure how to assign reviewers. I forgot to do it during the pull request.

**Comment by uniqueg** [comment]
No worries, we will review the pull request. Just please give us some time

**Comment by Dhryata** [comment]
@uniqueg Yes, thank you!

**Comment by uniqueg** [comment]
Closed in favor of #45

The code does a lot more than required and it is not very transparent what is going on. There is a merged solution for the issue that is precisely according to the specification (see #45). Focusing on the function that implements the expected functionality, the docstring is very well written. The loop is over multiple reads, but this was not the specified input (should be a single read), the comments are too extensive but not making the code easier to understand. Unit tests not implemented.

**Pull request closed without merging**
