### PR TITLE
feat: infer presence of polyA tail fragments

### LINKED ISSUE #86: Infer presence of polyA tails in reads
**Is your feature request related to a problem? Please describe.**
TBA

**Describe the solution you'd like**
TBA

**Describe alternatives you've considered**
TBA

**Additional context**
TBA

### PR DESCRIPTION
**Pull request by BorisYourich**
### Description

Added the cutadapt step in get_read_layout function. The report is parsed and the fraction of reads containing polyA tails is reported.

Also changed the __.readthedocs.yaml__ to use mamba instead of conda.

Fixes #86

### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality
      to not work as expected)
- [ ] Documentation update

### Checklist

Please carefully read these items and tick them off if the statements are true
_or do not apply_.

- [x] I have performed a self-review of my own code
- [x] My code follows the existing coding style, lints and generates no new
      warnings
- [x] I have added type annotations to all function/method signatures, and I
      have added type annotations for any local variables that are non-trivial,
      potentially ambiguous or might otherwise benefit from explicit typing.
- [x] I have commented my code in hard-to-understand areas
- [x] I have added ["Google-style docstrings"] to all new modules, classes,
      methods/functions or updated previously existing ones
- [x] I have added tests that prove my fix is effective or that my feature
      works
- [x] New and existing unit tests pass locally with my changes and I have not
      reduced the code coverage relative to the previous state
- [x] I have updated any sections of the app's documentation that are affected
      by the proposed changes

### CODE REVIEW

**Comment by BorisYourich** [comment]
I added the polyA_frac to README output example which I forgot previously. I also made the changes in the Dockerfile. Previously the Image used conda to install dependencies, I removed that and built from python:3.9-slim. The image is 416MB compared to 1.77GB previously, builds in 30 seconds compared to 30 minutes of the previous one, and also alleviates some overhead as repeatedly the htsinfer called on the test files paired adapters finished half a second earlier than the previous image.
The Codecov report seems rather strange, as locally the line-rate is 1 on my computer, and the Codecov page also doesn't mention any files which should contain missed lines.

**Review by uniqueg — CHANGES_REQUESTED** [review]
This is great!

Few minor comments:
- I strongly prefer to do one thing per feature branch/PR, because it makes the history cleaner, more precise and easily allows to roll back changes in case of issues. So I think the Dockerfile changes (which are great!) should really go in a different branch/PR, each with a properly phrased and formatted semantic/conventional commit message (https://www.conventionalcommits.org/en/v1.0.0/) as title (e.g., `build: Docker builds without Conda` and `feat: infer presence of polyA tail fragments`). Alternatively, you could use a single branch, but clean it up so that there is _exactly_ one clean commit per feature, again, using semantic commit messages. However, that is less preferred, because interactive rebasing of published branches is suboptimal - plus things get difficult if changes are requested (potenitally requires additional rebases).
- Don't think the CodeCov is your fault, it seems to have been there before. Perhaps you could open an issue for it so that we will get to the bottom of the problem and bring this back to 100% soon.

**Comment by uniqueg** [comment]
There is also this issue for the Read the Docs build (I tried rerunning but repeatedly got the same result): 
image

Not sure if this is because of the addition of Cutadapt, but we didn't have this before. Not sure if this would potentially work with Mamba, but then I'm not sure how to tell the Read the Docs build system to use Mamba instead of Conda... Other issues may be that there isn't a good channel listed for Cutadapt, or at least not for the specified version. This underlying issue could also explain why the Conda-based Docker build took so extremely long. Anyway, something seems wrong here...

**Comment by BorisYourich** [comment]
> There is also this issue for the Read the Docs build (I tried rerunning but repeatedly got the same result): image
> 
> Not sure if this is because of the addition of Cutadapt, but we didn't have this before. Not sure if this would potentially work with Mamba, but then I'm not sure how to tell the Read the Docs build system to use Mamba instead of Conda... Other issues may be that there isn't a good channel listed for Cutadapt, or at least not for the specified version. This underlying issue could also explain why the Conda-based Docker build took so extremely long. Anyway, something seems wrong here...

We might also try installing with pip, I didn't try in this commit but if it fails again I will push another one with cutadapt as pip dependency.

**Comment by BorisYourich** [comment]
Seems that there is no advantage to using pip to install cutadapt, anyway I have found this: https://docs.readthedocs.io/en/stable/guides/conda.html
So now it uses mamba... let's see.

**Comment by uniqueg** [comment]
Cool!

Guess I'll close this in favor of the two new PRs

**Pull request closed without merging**
